### ISSUE TITLE
A strange Error shows up and modules didn't get completed.

### ISSUE THREAD

**Issue by salooali** [SamJoan/droopescan#58]
I'm running a droopescan in a bash script. I've also tested it without a script the error is still showing up. I have a large list of hosts to scan can u please give me a hint if you have any clue why does this error occurs. I want to resolve it ASAP:
command:  droopescan scan drupal -u academy.neduet.edu.pk         
```
[+] Accepted redirect to https://academy.neduet.edu.pk/
 modules [ ===================                                ] 1451/4000 (36%)[+]  Got an HTTP 500 response.
modules [ =========================                          ] 1933/4000 (48%)[+]  Got an HTTP 500 response.
modules [ ============================                       ] 2238/4000 (55%)[+]  Got an HTTP 500 response.
modules [ =========================================          ] 3229/4000 (80%)Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='academy.neduet.edu.pk', port=443): Max retries exceeded with url: /modules/imagemagick/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

 ```

Please include:

* URL for site (if possible)
https://academy.neduet.edu.pk/

* Output of run with `--debug-requests`.

```
 droopescan scan drupal -u academy.neduet.edu.pk --debug-requests                                                                                                                                                                      2 ⨯
[head] http://academy.neduet.edu.pk/ None 302 
[+] Accepted redirect to https://academy.neduet.edu.pk/
[head] https://academy.neduet.edu.pk/sites/ None 403 
[head] https://academy.neduet.edu.pk/misc/drupal.js None 404 
[head] https://academy.neduet.edu.pk/core/misc/drupal.js None 200 
[head] https://academy.neduet.edu.pk/misc/test/error/404/ispresent.html None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/a12abb4d5bead1220174a6b39a2546db/ {} 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/ctools/ None [head] https://academy.neduet.edu.pk/sites/default/modules/a12abb4d5bead1220174a6b39a2546db/ {} 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/token/ None 404 
[head] https://academy.neduet.edu.pk/modules/contrib/a12abb4d5bead1220174a6b39a2546db/ {} 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/pathauto/ None 404 
[head] https://academy.neduet.edu.pk/modules/a12abb4d5bead1220174a6b39a2546db/ {} 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/views/ None 404 
404 
[head] https://academy.neduet.edu.pk/sites/all/modules/libraries/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/entity/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/webform/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/jquery_update/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/metatag/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/admin_menu/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/imce/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/date/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/field_group/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/google_analytics/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/ckeditor/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/captcha/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/module_filter/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/link/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/redirect/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/colorbox/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/views_bulk_operations/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/backup_migrate/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/features/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/rules/ None 404 
[head] https://academy.neduet.edu.pk/sites/all/modules/xmlsitemap/ None 404 

```

* OS & installation method (e.g. Kali Rolling installed via pip)
* OS:  Rooling kali  (2021.1)
Installation: via pip install droopescan

Thanks

**Comment by SamJoan** [comment]
Hi, 

I can't really comment on this until you clarify that you have permission to scan this large file of hosts.
